version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /Users/Diego Pelicce/Desktop
networks:
  postgres-compose-network:
    driver: bridge
