# Generated by Django 3.2.5 on 2021-07-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('data_horario', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarefaAgendada',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('id_horario_disponivel', models.CharField(max_length=5)),
                ('nome_cliente', models.CharField(max_length=255)),
            ],
        ),
    ]
