# Generated by Django 3.2.5 on 2021-07-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodisponivel',
            name='nome_barbeiro',
            field=models.CharField(default='', max_length=255),
        ),
    ]
