# Generated by Django 3.2.5 on 2021-07-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='data_horario',
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='data',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='horario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
